### ISSUE TITLE
Exporting XLIFF with duplicate keys in different namespaces mixes them up

### ISSUE THREAD

**Issue by DomiR** [tolgee/tolgee-platform#1983] opened 2023-11-09 08:40 UTC
We have different namespaces, but within the namespaces we have the same key multiple times. 
E.g. `alert.title` could be `"attention"` in namespace `a` and  `"warning"` in namespace `b`. 

When exporting XLIFF the source will be the same in all namespaces, e.g. `"attention"` for both `a` and `b`.

**Comment by siepkes** [comment] 2023-12-11 08:52
@DomiR Since we use XLIFF with Tolgee as well I thought it would be a good idea to fix this issue. 

However I can't seem to reproduce the issue. When I create a project (with `en` and `nl` as languages) with 2 namespaces and then create two keys with the same name in the separate namespaces with different values the XLIFF export looks as expected.

Which version of Tolgee did you encounter this issue with? I did my test with the Docker image of Tolgee `3.39.0`.

**Comment by JanCizmar** [comment] 2024-04-23 08:31
It looks like not reproducible, so I am closing this.

**Closed by JanCizmar** 2024-04-23 08:31 UTC
Labels: bug
