### ISSUE TITLE
Unexpected behaviour TOLGEE_AUTHENTICATION_NATIVE_ENABLED=false  with TOLGEE_AUTHENTICATION_REGISTRATIONS_ALLOWED=true

### ISSUE THREAD

**Issue by Megamannen** [tolgee/tolgee-platform#1944] opened 2023-10-12 14:06 UTC
A bit unsure on if this is really a fault or by design

But my aim was:
* Only google auth login
* No registration

First tried 
```env
TOLGEE_AUTHENTICATION_REGISTRATIONS_ALLOWED=false
TOLGEE_AUTHENTICATION_GOOGLE_CLIENT_ID=....
TOLGEE_AUTHENTICATION_GOOGLE_CLIENT_SECRET=....
TOLGEE_AUTHENTICATION_GOOGLE_WORKSPACE_DOMAIN=....
```
Then I couldn't login with users that hadn't logged in before. That was not what I expected, but I can understand the logic behind it.

So I activated registrations and disabled native. In my mind that would disable the native registration fields. That wasn't the case and I could register new users with it.
```env
TOLGEE_AUTHENTICATION_REGISTRATIONS_ALLOWED=false
TOLGEE_AUTHENTICATION_NATIVE_ENABLED=false
TOLGEE_AUTHENTICATION_GOOGLE_CLIENT_ID=....
TOLGEE_AUTHENTICATION_GOOGLE_CLIENT_SECRET=....
TOLGEE_AUTHENTICATION_GOOGLE_WORKSPACE_DOMAIN=....
```

The compose I run

```yaml
version: '3'

services:
  tolgee:
    env_file: .env
    image: tolgee/tolgee
    volumes:
      - tolgee-data:/data
    ports:
      - '8080:8080'

volumes:
  tolgee-data:
```

Native registration here
![image](https://github.com/tolgee/tolgee-platform/assets/19424456/b415cc7b-8b03-40fa-bc8b-2ee51c9f3d19)

**Comment by ammmze** [comment] 2023-10-12 22:52
That threw me for a loop at first too. But what I found was:

1. turn on native login
2. turn off registration
3. login with the initial admin account
4. go to organization settings > organization members > invite user
5. send invite for the oauth2 user you want to use and go through the invite process
6. turn off native login

So the gist is you have to invite any user you want to pull in from oauth2. Probably not ideal in some scenarios, but that is what I am intending to do as I start implementing Tolgee.

**Comment by JanCizmar** [comment] 2023-10-13 07:05
@cyyynthia would probably know, what's going on.

**Comment by cyyynthia** [comment] 2023-10-13 07:21
Hey there, I think this issue is a duplicate of #1716

The `native-enabled` config directive currently doesn't do much iirc, if anything (it is a remain from when LDAP authentication was supported, which is not the case anymore). I agree it's not the best way to deal with it, but it was left for this use case, when it'll be supported. Currently there's no "proper" way of doing this as of now unfortunately, but it's definitely something that should be supported at some point. 😄

**Comment by Megamannen** [comment] 2023-10-13 09:38
Yeah, it's the same as #1716

I'll do @ammmze workaround for now

**Comment by cyyynthia** [comment] 2023-10-13 12:16
Alrighty! I'll close this issue in favor of the already existing one then. Feel free to comment on the other thread if you wish to add some details or ask for some extra information, so all discussions happen at the same place. 😸

**Closed by cyyynthia** 2023-10-13 12:16 UTC
Labels: enhancement, duplicate
