### ISSUE TITLE
Error when importing keys that have html tags in their content

### ISSUE THREAD

**Issue by masebato** [tolgee/tolgee-platform#2483] opened 2024-09-23 21:20 UTC
**Describe the bug**
when importing translations from a json file that has in one of its values the key html tags, I get error when loading them.

**To Reproduce**
1. Go to proyect
2. Click on import
3. upload de file 

**Expected behavior**
I hope the file loads normally and I can import the keys.

**Screenshots**
![image](https://github.com/user-attachments/assets/620d61a2-b27e-4e22-9882-16d4e4a7accb)

![image](https://github.com/user-attachments/assets/6d24d90d-42b4-491c-a92a-ac83be69fdd5)

Example

![image](https://github.com/user-attachments/assets/53878414-f6a3-4262-af6a-e805648d9692)

**Comment by JanCizmar** [comment] 2024-09-24 05:28
Hey! It's not an error. It looks like you don't have permissions to edit keys.

**Comment by masebato** [comment] 2024-09-24 12:05
Thank you for your response. I have the admin role.

![image](https://github.com/user-attachments/assets/db6d7d59-d2bf-4246-ba76-dcc367a08351)

**Comment by JanCizmar** [comment] 2024-09-24 14:39
Weird! Can you please also share the exact file, you're importing? Also. Are you running self-hosted instance or do you use Tolgee Cloud?

**Comment by masebato** [comment] 2024-09-24 14:44
Sure! this is the file [translations.json](https://github.com/user-attachments/files/17116301/translations.json)

we are on a self hosted instance, the last version update was on 2024-08-21 (I don't know on which exact version it is running)

**Comment by Anty0** [comment] 2024-10-04 19:16
Thanks for the file! Unfortunately, I wasn't able to reproduce the issue using either the current version or v3.71.1. Would it be possible for you to provide server logs? Feel free to DM me on Slack (https://tolg.ee/slack) and send them there if you want to avoid posting them publicly.

**Comment by JanCizmar** [comment] 2024-10-09 11:03
Since we could not reproduce this, we are closing it for now. We will reopen it when more information is provided.

**Closed** 2024-10-09 12:18 UTC
