### ISSUE TITLE
Android: decode/encode HTML on import/export

### ISSUE THREAD

**Issue by Nailik** [tolgee/tolgee-platform#2186] opened 2024-03-14 08:57 UTC
Hi,

for Android HTML Tags in the string resources are only supported if they are encoded or if they are wrapped in `<![CDATA[...]]>`, Tolgee should support this.

**Comment by JanCizmar** [comment] 2024-03-14 09:00
Hello! So you mean, that we should reconginze <![CDATA[...]]> as a tag, right?

**Comment by Nailik** [comment] 2024-03-14 09:08
Depends how you want to Deal with it. We currently test Android/iOS and for iOS you need no `CDATA` but for Android.
Therefore i think adding an option to wrapped Android Text - at Export - with `<![CDATA[...]]>` (in the case it contains HTML Tags) is the simplest way.
Because iOS doesn't support encoded html

**Comment by JanCizmar** [comment] 2024-03-14 09:12
Oh, I am no sure I follow what's the expected behaviour. How does this kind of string with HTML tags get into the Tolgee Platform? Is it created manually or is it imported? What implications does it have for your project?

**Comment by Nailik** [comment] 2024-03-14 09:18
Okay i give an example.

We use links in the Strings.xml from android, like:

<string name="help_description"><![CDATA[For help please see <a href=\"someLink\">]]></string>.

This we import into Tolgee in order to Translate it but we want to use the exact same String/Id combination for our IOS Project because we use the same Text.

So i think we could in the future use for importing:
<string name="help_description">For help please see <a href=\"someLink\"></string>.

And then we need for export to Android:
<string name="help_description"><![CDATA[For help please see <a href=\"someLink\">]]></string>.


Maybe you could go another route and add an option to modify text while export via some Regex or Script Language?

**Comment by JanCizmar** [comment] 2024-03-14 09:48
Ok, now I follow. I have looked into that. Adding the option to export would be probably the right way. The only issue is that your strings can contain <xliff:g> tags, which are intended to be ignored by Android later, so `<xliff:g>`s would appear in your code.

**Comment by JanCizmar** [comment] 2024-03-14 10:06
Do you actually use the `<xliff:g>` or similar?

**Comment by Nailik** [comment] 2024-03-14 10:25
No only br, p and a

**Comment by Nailik** [comment] 2024-03-14 10:34
I just found out that indeed toglee seems to be encoding html tags in case that CDATA is not present! maybe there is nothing to do

**Comment by Nailik** [comment] 2024-03-15 10:27
I have some examples:
Import:
```
<string name="some_test_string">Some Link <a href="link">hier</a> some line breaks <br/><br/> more text</string>
<string name="some_test_string_encoded">Some Link &lt;a href=&quot;link&quot;&gt;hier&lt;/a&gt; some line breaks &lt;br/&gt;&lt;br/&gt; more text</string>
```

```
 <string name="some_test_string">
    Some Link 
    <a href="link">hier</a>
     some line breaks 
    <br/>
    <br/>
     more text
  </string>
  <string name="some_test_string_encoded">Some Link &lt;a href="link"&gt;hier&lt;/a&gt; some line breaks &lt;br/&gt;&lt;br/&gt; more text</string>
 ```
 
And that's all in all pretty weird. 

- Importing encoded HTML should decode it back to HTML
- Exporting to Android should encode HTML
- `&quot;` is decoded but not encoded on export

**Comment by JanCizmar** [comment] 2024-03-15 10:46
Thanks for exhaustive clarification! I am currently working on the fix. 

The plan:
For import: Remove the tags and quotes the same way as Android when parsing the xml resource file.
For export: Escape the tags and quotes, so it gets parsed by android correctly.

@stepan662 has the fix for the tag attributes on the to-do list, right?

**Comment by Nailik** [comment] 2024-03-15 10:53
For import: Remove the tags and quotes the same way as Android when parsing the xml resource file.
- Do you mean decoding it? `&lt;` -> `<` ?

**Comment by JanCizmar** [comment] 2024-03-15 11:26
Exactly. The plan is to use the parser from android, so it will import the same string as Android would render.

**Comment by stepan662** [comment] 2024-03-15 12:31
Ah, I see the problem. I'll add the support for self closing tags and arguments to the highlighter.

**Comment by Nailik** [comment] 2024-03-15 14:13
please remember about `%` sign
- if `%` is in a HTML text it needs to be `%%`
- if `%` is in a "normal" text it needs to be `\%`

**Comment by JanCizmar** [comment] 2024-03-15 14:42
Sorry in which context? Can you share some examples?

**Comment by Nailik** [comment] 2024-03-15 17:58
https://stackoverflow.com/questions/38466008/use-placeholder-with-sign-in-string-xml-for-string-format/38466118#38466118

explains it a little different

- %1$d use %%
- % without parameter use \u0025

I think there is some testing necessary to identify possible issues

**Comment by JanCizmar** [comment] 2024-03-19 11:05
Self-closing tags and tags with attributes are now supported (released an deployed on Tolgee Cloud) https://github.com/tolgee/tolgee-platform/pull/2194

**Closed** 2024-03-19 14:35 UTC

**Comment by JanCizmar** [comment] 2024-03-20 08:37
It's deployed on Tolgee Cloud now. 🚀 Here's the docs: https://tolgee.io/platform/formats/android_xml#strings-wrapped-with-cdata

**Comment by Nailik** [comment] 2024-03-20 08:46
So you use cdata now and have no option to use html encoding ?

**Comment by JanCizmar** [comment] 2024-03-20 08:57
It depends on the situation. Whole string is wrapped with CDATA when:
- there is the `_androidWrapWithCdata` custom value set on the key
- the string contains placeholders (e.g. `%s`) and tags in the same time
Element sequence is wrapped with CDATA when 
- the tag is not supported by Android (it's not listed [here](https://tolgee.io/platform/formats/android_xml#importing-keys-with-tags))

**Comment by Nailik** [comment] 2024-03-20 09:49
okay i found a small issue. When a string contains `%%` and a placeholder `%s` the placeholder is exported as second placeholder `%2$s` which is wrong

example:
```
import
<string name="test_percentage_and_param_correct">some %% with %s</string>
export
<string name="test_percentage_and_param_correct">some %% with %2$s</string>
```

**Comment by JanCizmar** [comment] 2024-03-20 10:00
A good catch! Thanks!

**Comment by JanCizmar** [comment] 2024-03-23 16:28
It's fixed in this PR: https://github.com/tolgee/tolgee-platform/pull/2183
