### ISSUE TITLE
Wrong keys count in some languages in project list

### ISSUE THREAD

**Issue by Thibault-Brocheton** [tolgee/tolgee-platform#1844] opened 2023-08-03 14:18 UTC
Just created a new project, it has 0 keys
![image](https://github.com/tolgee/tolgee-platform/assets/7646137/c5a25816-0986-48c3-b9d0-b3dc2efb4318)

In french and portugal, it displays 1 key   (1 clé / 1 chave)
![image](https://github.com/tolgee/tolgee-platform/assets/7646137/99b3d649-6498-4407-b829-465babcf7876)
![image](https://github.com/tolgee/tolgee-platform/assets/7646137/cd60b2f1-5d00-46ae-9471-044eb4b8e1fc)

Didn't found the issue in the fr.json & pt.json file, so I filed an issue rather than a PR

**Comment by Martin005** [comment] 2023-08-03 14:43
@Thibault-Brocheton Thanks for the report!
It seems that the issue is that currently, we always use `"1 X"` (`"1 clé"`, `"1 filtre"`,...) text for the **plural form "one"**. The issue is that [French](https://www.unicode.org/cldr/charts/43/supplemental/language_plural_rules.html#fr), [Portuguese](https://www.unicode.org/cldr/charts/43/supplemental/language_plural_rules.html#pt) (and several other languages) use the plural form "one" for the **both numbers 0 and 1**.
I will fix the texts on the back-end and the updates will be released on https://app.tolgee.io with a new version 🙂

**Comment by JanCizmar** [comment] 2023-08-07 07:29
Haha, nic one.

**Comment by Martin005** [comment] 2023-08-16 09:49
@JanCizmar I can see the fixed strings on dashboard:

![image](https://github.com/tolgee/tolgee-platform/assets/10096404/556bf38c-8feb-43fa-80bd-f32d6924fa68)

![image](https://github.com/tolgee/tolgee-platform/assets/10096404/998d46ea-9493-4ae1-9815-510adbb8ed1d)


And when I look at the network request for Portuguese, the key is properly pluralized:

![image](https://github.com/tolgee/tolgee-platform/assets/10096404/afe5c9c0-ab2e-4391-9d44-41d3f873c1b5)

**Comment by JanCizmar** [comment] 2023-08-16 10:10
Well, when I searched "1 clé" in the platform, I've got some results. Now after you fixed it looks fine, indeed.

**Closed** 2023-08-28 07:45 UTC
