### ISSUE TITLE
Accounts cannot be deleted

### ISSUE THREAD

**Issue by teawithfruit** [tolgee/tolgee-platform#2258] opened 2024-04-17 16:30 UTC
If there are more than 10 accounts in a self-hosted environment, it is not possible to delete or disable unnecessary accounts in the server administration. The error message `free_self_hosted_seat_limit_exceeded` is also displayed when deleting.

**Comment by JanCizmar** [comment] 2024-04-18 07:22
Hello, thanks for reporting. This is a duplicate of this #2219, we will address it soon. Sorry for inconvenience.

**Closed by JanCizmar** 2024-04-18 07:22 UTC

**Comment by JanCizmar** [comment] 2024-04-20 08:00
Fixed in #2267
